name: Build net

on:
  schedule:
    - cron: '0 22 * * 1,3,5' # runs at 00:00 CET Friday

  workflow_dispatch:

jobs:
        
  build_perf_rdma_host:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW RDMA host perf
      run: |
        mkdir build_perf_rdma_host_hw && cd build_perf_rdma_host_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=perf_rdma_host -DACLK_F=250
        make shell && make compile

    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: bitstream-perf-rdma-host
        path: build_perf_rdma_host_hw/bitstreams
        retention-days: 1

  build_perf_rdma_card:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW RDMA card perf
      run: |
        mkdir build_perf_rdma_card_hw && cd build_perf_rdma_card_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=perf_rdma_card -DACLK_F=250
        make shell && make compile

    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: bitstream-perf-rdma-card
        path: build_perf_rdma_card_hw/bitstreams
        retention-days: 1

  build_perf_rdma_sw:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile SW RDMA perf
      run: |
        mkdir build_perf_rdma_sw && cd build_perf_rdma_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/perf_rdma
        make

  build_perf_tcp:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW TCP/IP perf
      run: |
        mkdir build_perf_tcp_hw && cd build_perf_tcp_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=perf_tcp -DACLK_F=250
        make shell && make compile

    - name: Compile SW TCP/IP perf
      run: |
        mkdir build_perf_tcp_sw && cd build_perf_tcp_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/perf_tcp/
        make
