name: Build base

on:
  schedule:
    - cron: '0 22 * * *' # runs at 00:00 CET

  workflow_dispatch:

jobs:

  build_perf_host:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile HW Perf Host Example
      run: |
        mkdir build_perf_host_hw && cd build_perf_host_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=perf_host
        make shell && make compile
    
    - name: Compile SW Perf Host Example
      run: |
        mkdir build_perf_host_sw && cd build_perf_host_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/perf_host
        make
    
    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: bitstream-perf-host
        path: build_perf_host_hw/bitstreams
        retention-days: 1
        
  build_perf_fpga:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile HW Perf FPGA Example
      run: |
        mkdir build_perf_fpga_hw && cd build_perf_fpga_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=perf_fpga
        make shell && make compile
    
    - name: Compile SW Perf FPGA Example
      run: |
        mkdir build_perf_fpga_sw && cd build_perf_fpga_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/perf_fpga
        
    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: bitstream-perf-fpga
        path: build_perf_fpga_hw/bitstreams
        retention-days: 1

  build_gbm_dtrees:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Gradient Boosting Dtrees
      run: |
        mkdir build_gbm_dtrees_hw && cd build_gbm_dtrees_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=gbm_dtrees
        make shell && make compile

    - name: Compile SW Gradient Boosting Dtrees
      run: |
        mkdir build_gbm_dtrees_sw && cd build_gbm_dtrees_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/gbm_dtrees
        make

    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: bitstream-gbm-dtrees
        path: build_gbm_dtrees_hw/bitstreams
        retention-days: 1
        
  build_hyperloglog:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Hyperloglog
      run: |
        mkdir build_hyperloglog_hw && cd build_hyperloglog_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=hyperloglog
        make shell && make compile

    - name: Compile SW Hyperloglog
      run: |
        mkdir build_hyperloglog_sw && cd build_hyperloglog_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/hyperloglog
        make
    
    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: bitstream-hyperloglog
        path: build_hyperloglog_hw/bitstreams
        retention-days: 1
  
  build_service_aes:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Service AES
      run: |
        mkdir build_service_aes_hw && cd build_service_aes_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=service_aes
        make shell && make compile

    - name: Compile SW Service AES Client
      run: |
        mkdir build_service_aes_sw_client && cd build_service_aes_sw_client
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/service_aes/client
        make

    - name: Compile SW Service AES Service
      run: |
        mkdir build_service_aes_sw_service && cd build_service_aes_sw_service
        /usr/bin/cmake ../sw/ -DTARGET_DIR=examples/service_aes/service
        make

    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: bitstream-service-aes
        path: build_service_aes_hw/bitstreams
        retention-days: 1
