name: Build base

on:
  schedule:
    - cron: '0 22 * * *' # runs at 00:00 CET

  workflow_dispatch:

jobs:

  build_bmark_host:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile HW Benchmark Host Example
      run: |
        mkdir build_bmark_host_hw && cd build_bmark_host_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=bmark_host
        make shell && make compile
    
    - name: Compile SW Benchmark Host Example
      run: |
        mkdir build_bmark_host_sw && cd build_bmark_host_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=../sw/examples/bmark_host
        make
        
  build_bmark_fpga:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile HW Benchmark FPGA Example
      run: |
        mkdir build_bmark_fpga_hw && cd build_bmark_fpga_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=bmark_fpga
        make shell && make compile
    
    - name: Compile SW Benchmark FPGA Example
      run: |
        mkdir build_bmark_fpga_sw && cd build_bmark_fpga_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=../sw/examples/bmark_fpga
        
  build_gbm_dtrees:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Gradient Boosting Dtrees
      run: |
        mkdir build_gbm_dtrees_hw && cd build_gbm_dtrees_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=gbm_dtrees
        make shell && make compile

    - name: Compile SW Gradient Boosting Dtrees
      run: |
        mkdir build_gbm_dtrees_sw && cd build_gbm_dtrees_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=../sw/examples/gbm_dtrees
        make
        
  build_hyper_log_log:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Hyperloglog
      run: |
        mkdir build_hyper_log_log_hw && cd build_hyper_log_log_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=hyper_log_log
        make shell && make compile

    - name: Compile SW Hyperloglog
      run: |
        mkdir build_hyper_log_log_sw && cd build_hyper_log_log_sw
        /usr/bin/cmake ../sw/ -DTARGET_DIR=../sw/examples/hyperloglog
        make
  
  build_service_aes:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Compile HW Service AES
      run: |
        mkdir build_service_aes_hw && cd build_service_aes_hw
        /usr/bin/cmake ../hw/ -DFDEV_NAME=u55c -DEXAMPLE=service_aes
        make shell && make compile

    - name: Compile SW Service AES Client
      run: |
        mkdir build_service_aes_sw_client && cd build_service_aes_sw_client
        /usr/bin/cmake ../sw/ -DTARGET_DIR=../sw/examples/service_aes/client
        make

    - name: Compile SW Service AES Service
      run: |
        mkdir build_service_aes_sw_service && cd build_service_aes_sw_service
        /usr/bin/cmake ../sw/ -DTARGET_DIR=../sw/examples/service_aes/service
        make
